esphome:
  name: front-hall-status-lights

esp8266:
  board: d1_mini
  framework:
    version: 2.7.4

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "0da2985c26d820305209ce04ed798d99"

wifi:
  ssid: FlooNetworkDownstairs
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Front-Hall-Status-Lights"
    password: "zgTrFurgCDFO"

captive_portal:

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: D2
    num_leds: 3
    rgb_order: GRB
    id: light1
  - platform: partition
    name: "Mail Light"
    segments:
      - id: light1
        from: 0
        to: 0
  - platform: partition
    name: "Trash Light"
    segments:
      - id: light1
        from: 1
        to: 1
  - platform: partition
    name: "Recycle Light"
    segments:
      - id: light1
        from: 2
        to: 2
        
sensor:
    
  - platform: wifi_signal
    name: "Front Hall Status Lights WiFi Signal"
    update_interval: 60s
    
  - platform: uptime
    name: "Front Hall Status Lights Uptime"
    id: front_hall_status_lights_uptime
    update_interval: 60s
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: front_hall_status_lights_uptime_human
            state: !lambda |-
              int seconds = round(id(front_hall_status_lights_uptime).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? to_string(days) + "d " : "") +
                (hours ? to_string(hours) + "h " : "") +
                (minutes ? to_string(minutes) + "m " : "") +
                (to_string(seconds) + "s")
              ).c_str();

text_sensor:
  - platform: template
    name: Front Hall Status Lights Uptime Human Readable
    id: front_hall_status_lights_uptime_human
    icon: mdi:clock-start
    entity_category: diagnostic

binary_sensor:
  - platform: gpio
    pin:
      number: D5
      inverted: true
      mode:
        input: true
        pullup: true
    id: button1
    name: "Mail Button"
    icon: "mdi:mailbox"
  - platform: gpio
    pin:
      number: D6
      inverted: true
      mode:
        input: true
        pullup: true
    id: button2
    name: "Trash Button"
    icon: "mdi:trash-can"
  - platform: gpio
    pin:
      number: D7
      inverted: true
      mode:
        input: true
        pullup: true
    id: button3
    name: "Recycle Button"
    icon: "mdi:recycle"