esphome:
  name: patio-sensors

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "bea1d3580748e5b6cef69b3c197458b1"

wifi:
  ssid: !secret wifi_downstairs_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Patio-Sensors Fallback Hotspot"
    password: "9LcFkgwJCsBo"

captive_portal:
    
spi:
  clk_pin: 18
  mosi_pin: 23
  miso_pin: 19

as3935_spi:
  cs_pin: 5
  irq_pin: 14
  indoor: false
  spike_rejection: 11
  
i2c:
  sda: 21
  scl: 22
  scan: true
  id: bus_a
    
    
# Example lightning and energy sensor
sensor:
  - platform: as3935
    lightning_energy:
      name: "Lightning Energy"
    distance:
      name: "Distance Storm"
      
  - platform: bh1750
    name: "Patio Ambient Light"
    address: 0x23
    update_interval: 60s
  
  - platform: dht
    pin: 32
    temperature:
      name: "Patio Temperature"
    humidity:
      name: "Patio Humidity"
    model: DHT22
    update_interval: 60s
    
  - platform: wifi_signal
    name: "Patio Sensors WiFi Signal"
    update_interval: 60s
    
  - platform: uptime
    name: "Patio Sensors Uptime"
    id: patio_sensors_uptime
    update_interval: 60s
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: patio_sensors_uptime_human
            state: !lambda |-
              int seconds = round(id(patio_sensors_uptime).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? to_string(days) + "d " : "") +
                (hours ? to_string(hours) + "h " : "") +
                (minutes ? to_string(minutes) + "m " : "") +
                (to_string(seconds) + "s")
              ).c_str();

text_sensor:
  - platform: template
    name: Patio Sensors Uptime Human Readable
    id: patio_sensors_uptime_human
    icon: mdi:clock-start
    entity_category: diagnostic
    
binary_sensor:
  - platform: as3935
    name: "Storm Alert"
    
  - platform: gpio
    pin: 27
    name: "Patio Motion"
    device_class: motion