# These buttons get pressed by the alexa routine, thereby triggering an automation in HA
input_button:
  # Weather
  alexa_weather_check:
    name: Alexa Weather Check
    icon: mdi:sun-wireless
    # what's the weather
    # check the weather
    # what's the weather like
    # what's the weather right now
    # how's it look outside
    # what's the weather currently
    # what's the current weather

  alexa_weather_forecast:
    name: Alexa Weather Forecast
    icon: mdi:weather-cloudy-clock
    # what's the forecast
    # what's the weather going to be like tomorrow
    # what's the weather going to be today
    # what's the weather going to be like today
    # what's the forecast for tomorrow
    # what's the forecast for this weekend
    # what's the weather going to be like later

  alexa_weather_rain_check:
    name: Alexa Weather Rain Check
    icon: mdi:weather-pouring
    # is it going to rain
    # is it going to rain today
    # should i bring an umbrella
    # should i bring an umbrella today
    # is it gonna rain
    # is it gonna rain today

  alexa_weather_temperature_check:
    name: Alexa Weather Temperature Check
    icon: mdi:weather-pouring
    # what's the temperature
    # what's the current temperature
    # what's the temperature right now
    # what's the temperature outside
    # what's the temp outside
    # what's the temp

  # Locations
  alexa_location_of_chris:
    name: Alexa Location Of Chris
    icon: mdi:map-marker-account
    # where's chris
    # where is chris
    # what's chris's location
    # where's chris at
    # what's chris up to

  alexa_location_of_steven:
    name: Alexa Location Of Steven
    icon: mdi:map-marker-account
    # where's steven
    # where is steven
    # what's steven's location
    # where's steven at
    # what's steven up to

  # Miscellaneous
  alexa_set_the_mood:
    name: Alexa Set The Mood
    icon: mdi:robot-love
    # set the mood

  alexa_what_to_eat:
    name: Alexa What To Eat
    icon: mdi:food
    # what should we eat
    # i'm hungry
    # where should we eat
    # what should we order
    # where should we order
    # where should we order from
    # recommend a restaurant

  alexa_introduce_yourself:
    name: Alexa Introduce Yourself
    icon: mdi:human-greeting-variant
    # present yourself
    # introduce yourself
    # say hi
    # show yourself off
    # show off
    # show them what you do
    # show them what you can do

automation:
  - id: alexa_weather_check
    alias: Alexa Weather Check
    initial_state: true
    trigger:
      platform: state
      entity_id:
        - input_button.alexa_weather_check
    action:
      service: script.alexa_voice
      data:
        who: presence
        message: ""

  - id: alexa_weather_forecast
    alias: Alexa Weather Forecast
    initial_state: true
    trigger:
      platform: state
      entity_id:
        - input_button.alexa_weather_forecast
    action:
      service: script.alexa_voice
      data:
        who: presence
        message: ""

  - id: alexa_weather_rain_check
    alias: Alexa Weather Rain Check
    initial_state: true
    trigger:
      platform: state
      entity_id:
        - input_button.alexa_weather_rain_check
    action:
      service: script.alexa_voice
      data:
        who: presence
        message: >
          {%- if states("sensor.openweathermap_weather") in ["thunderstorm"] -%}
            {{ [
              "Do you not hear the thunder out there? ",
              "According to my sensors, there should actually be some thunder out there. ",
              "It's probably storming right now. But I can only work with what I've got so what do I really know? "
            ] | random }}
          {%- elif states("sensor.openweathermap_weather") in ["moderate rain"] -%}
            {{ [
              "It's probably raining right now. If not, it probably will. But it's Florida, so who knows ",
              "According to my sensors, it should be raining pretty well right about now. ",
              "It should be raining right now. But I can only work with what I've got so what do I really know? "
            ] | random }}
          {%- elif states("sensor.openweathermap_weather") in ["light rain","mist"] -%}
            {{ [
              "It's probably raining a little bit right now actually. If not, it probably will. You know, Florida. ",
              "According to my sensors, it's probably drizzling out. Take a look. ",
              "It might actually be raining slightly right now. But I can only work with what I've got so what do I really know? "
            ] | random }}
          {%- else -%}
            {{ state_attr("sensor.precipitation_forecast", "next_rain_timeframe") }}
          {%- endif -%}

  - id: alexa_weather_temperature_check
    alias: Alexa Weather Temperature Check
    initial_state: true
    trigger:
      platform: state
      entity_id:
        - input_button.alexa_weather_temperature_check
    action:
      service: script.alexa_voice
      data:
        who: presence
        message: ""

  - id: alexa_location_of_chris
    alias: Alexa Location Of Chris
    initial_state: true
    trigger:
      platform: state
      entity_id:
        - input_button.alexa_location_of_chris
    action:
      service: script.alexa_voice
      data:
        who: presence
        message: ""

  - id: alexa_location_of_steven
    alias: Alexa Location Of Steven
    initial_state: true
    trigger:
      platform: state
      entity_id:
        - input_button.alexa_location_of_steven
    action:
      service: script.alexa_voice
      data:
        who: presence
        message: ""

  - id: alexa_set_the_mood
    alias: Alexa Set The Mood
    initial_state: true
    trigger:
      platform: state
      entity_id:
        - input_button.alexa_set_the_mood
    action:
      service: script.alexa_voice
      data:
        who: presence
        message: ""

  - id: alexa_what_to_eat
    alias: Alexa What To Eat
    initial_state: true
    trigger:
      platform: state
      entity_id:
        - input_button.alexa_what_to_eat
    action:
      service: script.alexa_voice
      data:
        who: presence
        message: ""

  - id: alexa_introduce_yourself
    alias: Alexa Introduce Yourself
    initial_state: true
    trigger:
      platform: state
      entity_id:
        - input_button.alexa_introduce_yourself
    action:
      service: script.alexa_voice
      data:
        who: presence
        message: ""
