#####################################################################
# @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
## Plays the number of cuckoos per hour and 1 on the half hour.
# More Info and Video: https://www.vcloudinfo.com/2017/11/building-digital-cuckoo-clock-with-home.html

# Modified by Chris Heder (@chrisron95)
# Setup package to make everything configurable.
# Added:
#   - Ability to select sound between Cuckoo and Grandfather Clock
#   - Quarter toll ability
#   - Ability to disable quarter and half tolls, and chime entirely
#
# Changed:
#   - Now runs every 15 minutes rather than only every half hour
#   - Triggers have IDs now which allows me to replace the time templates
#####################################################################

input_boolean:
  clock_chime:
    name: Clock Chime
    icon: mdi:alarm
  clock_chime_half_toll:
    name: Clock Chime Half Hour Toll
    icon: mdi:alarm
  clock_chime_quarter_toll:
    name: Clock Chime Quarter Hour Toll
    icon: mdi:alarm

input_select:
  clock_chime_sound:
    name: Clock Chime Sound
    options:
      - Cuckoo Clock
      - Grandfather Clock
    icon: mdi:bell-ring

automation:
  - alias: Clock Chime
    id: clock_chime
    mode: restart
    # Trigger every 15 minutes. The ID lets you know which one is current, rather than a time template.
    # This accounts for the delay when waiting for media player to stop playing, just in case it lasts too long.
    trigger:
      - platform: time_pattern
        minutes: 0
        id: "0"
      - platform: time_pattern
        minutes: 15
        id: "15"
      - platform: time_pattern
        minutes: 30
        id: "30"
      - platform: time_pattern
        minutes: 45
        id: "45"

    condition:
      - condition: state
        entity_id: input_boolean.audible_notifications
        state: "on"
      - condition: state # Make sure the chime is enabled.
        entity_id: input_boolean.clock_chime
        state: "on"
      - condition: or # Either we are home or Guest_Mode is on.
        conditions:
          - condition: state
            entity_id: group.family
            state: "home"
          - condition: state
            entity_id: input_boolean.guest_mode
            state: "on"

    action:
      - choose:
          # Check for quarter and half hour trigger, and stop if it should be disabled.
          - conditions:
              - condition: or
                conditions:
                  - condition: trigger
                    id: "15"
                  - condition: trigger
                    id: "45"
            sequence:
              - condition: or
                conditions:
                  # Don't play the quarter toll if it's disabled.
                  - condition: state
                    entity_id: input_boolean.clock_chime_quarter_toll
                    state: "off"
                  # Also don't play the quarter toll if Cuckoo Clock is selected as it's not needed.
                  - condition: state
                    entity_id: input_select.clock_chime_sound
                    state: Cuckoo Clock
              - stop: "Quarter Toll Disabled"
          - conditions:
              - condition: trigger
                id: "30"
            sequence:
              # Don't play the half toll if it's disabled.
              - condition: state
                entity_id: input_boolean.clock_chime_half_toll
                state: "off"
              - stop: "Half Toll Disabled"
        default: []
      - wait_template: '{{ not is_state("media_player.living_room_echo", "playing") }}'
        continue_on_timeout: false
        timeout: "00:02:00" # Only give it two minutes then give up, otherwise what's the point?
      - service: script.alexa_voice
        data:
          who: living_room
          message: > # Use the trigger ID to specify which sound to play.
            {% if states("input_select.clock_chime_sound") == "Cuckoo Clock" %}
              {% if trigger.id == "30" %}
                <audio src='https://heder-homeassistant.s3.amazonaws.com/cuckoo-clock/cuckoo-clock-01.mp3'/>
              {% else %}
                <audio src='https://heder-homeassistant.s3.amazonaws.com/cuckoo-clock/cuckoo-clock-{{now().strftime("%I")}}.mp3'/>
              {% endif %}
            {% elif states("input_select.clock_chime_sound") == "Grandfather Clock" %}
              {% if trigger.id == "15" %}
                <audio src='https://heder-homeassistant.s3.amazonaws.com/gf-clock/toll-1quarter.mp3'/>
              {% elif trigger.id == "30" %}
                <audio src='https://heder-homeassistant.s3.amazonaws.com/gf-clock/toll-2quarter.mp3'/>
              {% elif trigger.id == "45" %}
                <audio src='https://heder-homeassistant.s3.amazonaws.com/gf-clock/toll-3quarter.mp3'/>
              {% else %}
                <audio src='https://heder-homeassistant.s3.amazonaws.com/gf-clock/{{now().strftime("%I")}}-hour.mp3'/>
              {% endif %}
            {% endif %}
